cooperlees/monitord

- .github/dependabot.yml
- Cargo.toml
- Move version to release to crates.io
- Pinning deps to make importing to $big company easier
- Stop dependbot updating deps ... Will move with $big company each release
Test: Ensure tests still pass and run locally on Linux box
> Move to 0.2.0 and pin versions for $big company

- README.md
- monitord.conf
- src/lib.rs
- src/networkd.rs
- src/units.rs
- Add monitord dbus_address config param
- Allow it to be option and fallback to a default
Test: `cargo run -- -v -c monitord.conf`
Fixes #14
> Allow config driven DBUS Address to be set

- monitord.conf
- src/json.rs
- src/lib.rs
- Allow a config drive prefix to flat json keys
- THe key will be prefix with the value and a automatic period `.`
Test:
- Add unittest showing keys with prefix
- keep all existing unittests passing
- Run with a `monitord` key_prefix set:
- `cargo run -- -c monitord.conf`
Fixes #20
> Support a key prefix for flat-json

- src/lib.rs
- src/networkd.rs
- src/units.rs
- Pass in DBUS socket address always - either CLI or default
- Move DEFAULT into lib.rs
Fixes #23
> Pass dbus from lib.rs to other modules

- monitord.conf
- src/json.rs
- We can have a mix of ints, lets support them correctly
- This format is needed for some monitors systems used
Test:
- Add unittests to have a negative `status_errno` value (-69)
- Asset we render correctly showing -69
- `test_flatten` test ensures we're valid JSON via oxidized_json_checker
> Move json-flat to handle i32, u32 + U64s

- src/json.rs
- src/lib.rs
- Had issues unwrapping_or to a HashMap compiling in some environments
- We only need an empty vector, so lets use a match statement to do so if the config has no `[services]` section
- Add in fix to not log service_stats as a missed field in flatten_units
Test:
- Remove `[services]` from monitord.conf and test running
- `cargo run -c monitord.conf -vv`
> Move default services to collect stats on to a match statement

- Cargo.toml
- README.md
- src/json.rs
- src/lib.rs
- src/logging.rs
- src/main.rs
- src/networkd.rs
- src/units.rs
- tracing is the hostness for logging these days, lets use it
- Move to widely adopted glog format with local system time
- Move to version 0.5.0 + due to changing logging libraries
Test:
- See all CI pass
- Run and see logging still
> Move to tracing for logging

- src/units.rs
- Create small function to handle if we have no processes rather than assuming we always have a running process
Test:
- Add unittest
- Run with a non running service in the monitord.conf
Addresses part of #47
> Fix handling of units with no running processes

- README.md
- monitord.conf
- src/json.rs
- src/lib.rs
- src/units.rs
- Add a new HashMap of UnitStates structs to hold per unit states
- We only do ActiveState and LoadedState
- Add config to
- Enable state collection
- Allow list of units to collect state for
- Block list of units to colelct state for
Tests:
- Add unittest for parse_state
- Add unit state to JSON unittests
- Run on my fedora box to see the state stats for chonry + sshd
- `cargo run -- -l debug -c monitord.conf`
```
Finished dev [unoptimized + debuginfo] target(s) in 0.03s
Running `target/debug/monitord -l debug -c monitord.conf`
I0914 15:39:38.590418 823276 src/main.rs:28] monitord: Know how happy your systemd is! 😊
D0914 15:39:38.590504 823276 src/main.rs:29] CLI Args: Cli { config: "monitord.conf", log_level: Debug }
D0914 15:39:38.590542 823276 src/main.rs:30] Loading "monitord.conf" …
```
> Add per unit state stats

- README.md
- monitord.conf
- src/json.rs
- src/lib.rs
- src/system.rs
If set in config, pull the system state
- Know if we've started up cleanly or not ...
Tests:
- Add to JSON tests
> Add system-state metric

- src/units.rs
In checking we handed inactive units correctly I found we were missing not-found.
Added support for that into enum. Had to rename the passed in str replaceing `-` with `_`.
> [unit_states] Support not-found unit state

- src/networkd.rs
- src/system.rs
- src/units.rs
- We now get Display support using strum::Display macro
> Remove all uses of strum_macros::ToString macro

- monitord.conf
- src/config.rs
- src/lib.rs
- src/main.rs
- src/networkd.rs
- src/units.rs
- Let's not make library users use ConfigParser IndexMaps
- Make dedicated structs and enum
- Also allows cleanup of code as all parsing of config done in the config module now
- Implement useful traits
- Move code to using new `Config` struct
- Fix bug: Convert config seconds to milliseconds (missed multiplying by 1000)
Test:
- Add + fix tests
- Run on my test box
```
cargo run -- -c monitord.conf
```
- Play with changing config settings and see them applied
> Add dedicated config structs

- LICENSE
This matches `Cargo.toml`; the inconsistency was detected during the Fedora review process.
> Switch license file from LGPL 2.1 to GPL 2

- src/units.rs
- If a unit is not loaded, let's not mark it as unhealthy
- Add function to do this simple logic + so we can unit test it to ensure it behaves how we want
- Let's assume the admin if the system(s) running monitord know what they are doing and have marked it / non loaded / deleted it etc. on purpose
- People can use dedicated !loaded checks if they want to find units in specific states
- "Unhealthy" means !active only when loaded ...
Test:
Add unit test showing function doing what we expect
> Make unit unhealthy check only care about LoadState::loaded

- src/lib.rs
- src/main.rs
- src/networkd.rs
- src/pid1.rs
- src/system.rs
- src/units.rs
- Now that we have an async dbus client, lets make this function
- Add an update_*_stats API in each module + pass a RWLocked stats struct to update
- Join and check for any errors + log etc.
Test Plan:
- Run and see same stats
- Didn't notice much runtime win here ... down from 12-13ms to 11-12ms
- 10ms if I disable networkd
- Still got some networkd I/O to make async ... will do that in a follow up dedicated PR
```
cooper@cooper-fedora-MJ0J8MTZ:~/repos/monitord$ ls -lh target/release/monitord
-rwxr-xr-x. 2 cooper cooper 3.5M Oct  1 09:04 target/release/monitord
cooper@cooper-fedora-MJ0J8MTZ:~/repos/monitord$ time ./target/release/monitord -c monitord.conf > /dev/null
I1001 09:05:16.258015 3289269 src/main.rs:28] monitord: Know how happy your systemd is! 😊
I1001 09:05:16.258750 3289269 …
```
> Refactor stat_collector to run all collections in async parallel

- Cargo.toml
- For non Cargo build we need explicit versions for the derived macro expansion
- Big Company that uses this needs that explictly
So we only support dbus 4 still, except in cargo worlds.
> Move back to hard pinned zbus versions

- Cargo.toml
In a previous commit, default features were disable to optimize release binary size, but this broke the `--help` functionality mentioned in the README of monitord.
This is the output from a default install from crates.io
```
Installed package `monitord v0.12.0` (executable `monitord`)                                │
❯ monitord --help                                                                              │  -V, --version
error: unexpected argument found
```
With this PR we just add the help feature. This still keeps the binary small
```
-rwxr-xr-x 2 vasuper vasuper 2.3M Jan 10 21:58 monitord
```
> fix: restore clap help feature

- src/json.rs
- src/units.rs
- Here we add a calculation of microseconds since the state of this unit last changed
- This could be handy to know to see if multiple units all started failing around the same time or if a service(s) are flapping states
Test:
- Keep unittests passing
- Run locally and see calculations seem sane
- Had to install openssh-server to see it on my docker container
```
[root@b89a51f4c266 repo]# cargo run -- -c monitord.conf
...
I0315 02:57:15.529738  5905 src/lib.rs:182] stat collection run took 18ms
...
"monitord.unit_states.sshd.service.active_state": 1,
"monitord.unit_states.sshd.service.load_state": 1,
"monitord.unit_states.sshd.service.time_in_state_usecs": 1302552480,
...
```
- Restarted sshd to see the number much lower
```
"monitord.unit_states.sshd.service.time_in_state_usecs": …
```
> Add time_in_state_usec to unit states

- monitord.conf
- src/config.rs
- src/json.rs
- src/timer.rs
- src/units.rs
Let's add some timer stats to collected values. We've had some bugs/issues with timers so it's been request we get some metrics around them.
People can then add this to timeseries databases and alarm if they calculate timers are not running enough ...
Here we:
- Collect all information systemd gives us specific to timers
- Will be used to monitor timers are running as we'd hoped/configured
- Add collection of all values to timers.rs
- Also pull service unit + it's last state change times too to check
it triggers at the interval it should ...
- Move error reporting to units.rs for each timer unit
- Add "Flat JSON" support + update tests
- Even test for machine support
- Add enable / disable config
- Will add allow list + deny list in another diff
- Want to share code already in use for …
> Add Timer stats

- src/json.rs
- src/timer.rs
- Call everything in parallel via tokio::join!
- Also only lookup service unit timers should a timer have a unit set
- Not sure if it's possible to have a timer without a service but caters for it
Does not seems to be faster ... But I feel the code is cleaner.
Test:
```
cooper@cooper-fedora-MJ0J8MTZ:~/repos/monitord$ cargo build --release
cooper@cooper-fedora-MJ0J8MTZ:~/repos/monitord$ ./target/release/monitord -c monitord.conf | grep '\.timers' | head
...
I0404 11:50:37.162290 1850555 src/lib.rs:182] stat collection run took 80ms
...
cooper@cooper-fedora-MJ0J8MTZ:~/repos/monitord$ cargo build --release
cooper@cooper-fedora-MJ0J8MTZ:~/repos/monitord$ ./target/release/monitord -c monitord.conf | grep '\.timers' | head
...
I0404 11:51:50.310913 1852422 src/lib.rs:182] stat collection run …
```
> [timers] Call all DBUS calls in parallel

- src/config.rs
- src/json.rs
- src/units.rs
- This collection is expensive (zbus call per unit)
- Add a bool to enable it or not in config
- To make it clear, represent the stat as optional to know when disabled
- If null, don't print in flat JSON
Test:
- Keep unittests passing
- Show we handle optional not seeing in flat JSON
- Other formats will show null
> Make units time_in_state optional

- README.md
- Dbus and Varlink (no varlink yet)
- Wanted to talk be able to share with systemd people what we call in easy readable list
> Add Monitord dependency API usage

- Cargo.toml
- src/lib.rs
- src/machines.rs
zbus version 5.11 added new `method_timeout` API. We should use it instead of custom tokio timeouts.
> Use zbus `method_timeout` instead of tokio timeouts
